# Set prefix to ctrl-space (normally ctrl-b)
unbind C-b
set -g prefix C-Space

# Open new/split panes with the path of the current pane
unbind c
bind c new-window -c '#{pane_current_path}'

# Intuitive window-splitting keys
bind | split-window -h -c '#{pane_current_path}' # normally prefix-%
bind \\ split-window -h -c '#{pane_current_path}' # normally prefix-%
bind - split-window -v -c '#{pane_current_path}' # normally prefix-

# Set terminal to 256 colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

# Set history limit to go back
set -g history-limit 4096

# Highlight active window
set -w -g window-status-current-style bg=red

# Disable mouse to avoid colissions between tmux and vim
set -g mouse off

# Automatically renumber window numbers on closing a pane (tmux >= 1.7)
set -g renumber-windows on

# Start window and pane numbering at 1 (0 is too hard to reach)
set -g base-index 1
set -g pane-base-index 1

# Don't wait for an escape esquence after seeing C-Space
set -s escape-time 0

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @plugin 'tmux-plugins/tmux-resurrenct'

# tmux-resurrenct for neovim
set -g @russurrect-strategy-nvim 'session'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
